/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/system/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** System Status */
        get: operations["system_status_api_v1_system_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agents */
        get: operations["list_agents_api_v1_agents_get"];
        put?: never;
        /** Create Agent */
        post: operations["create_agent_api_v1_agents_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/derive": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Derive Agent */
        post: operations["derive_agent_api_v1_agents_derive_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Agent */
        get: operations["read_agent_api_v1_agents__agent_id__get"];
        put?: never;
        post?: never;
        /** Archive Agent */
        delete: operations["archive_agent_api_v1_agents__agent_id__delete"];
        options?: never;
        head?: never;
        /** Patch Agent */
        patch: operations["patch_agent_api_v1_agents__agent_id__patch"];
        trace?: never;
    };
    "/api/v1/agents/{agent_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agent State */
        get: operations["agent_state_api_v1_agents__agent_id__state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agent Tasks */
        get: operations["agent_tasks_api_v1_agents__agent_id__tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Agent Activity */
        get: operations["agent_activity_api_v1_agents__agent_id__activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Agent Message */
        post: operations["agent_message_api_v1_agents__agent_id__message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Route Message */
        post: operations["route_message_api_v1_message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{agent_id}/run": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Run Agent */
        post: operations["run_agent_api_v1_agents__agent_id__run_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/tasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tasks */
        get: operations["tasks_api_v1_tasks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Activity */
        get: operations["activity_api_v1_activity_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Events */
        get: operations["events_api_v1_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Models */
        get: operations["models_api_v1_models_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dashboard/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Dashboard Overview */
        get: operations["dashboard_overview_api_v1_dashboard_overview_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/project-summaries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Project Summaries */
        get: operations["project_summaries_api_v1_project_summaries_get"];
        put?: never;
        /** Ingest Project Summary */
        post: operations["ingest_project_summary_api_v1_project_summaries_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Stream */
        get: operations["stream_api_v1_stream_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Activity */
        Activity: {
            /** Id */
            id: number;
            /** Agent Id */
            agent_id?: string | null;
            /** Message */
            message: string;
            /**
             * Level
             * @default info
             */
            level: string;
            /**
             * Metadata
             * @default {}
             */
            metadata: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at: string;
        };
        /** Agent */
        Agent: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Icon
             * @default ◌
             */
            icon: string;
            /**
             * Category
             * @default general
             */
            category: string;
            /** Enabled */
            enabled: boolean;
            status: components["schemas"]["AgentStatus"];
            /**
             * System Instructions
             * @default
             */
            system_instructions: string;
            privacy_class: components["schemas"]["PrivacyClass"];
            model_policy: components["schemas"]["ModelPolicy"];
            /**
             * Allowed Tools
             * @default []
             */
            allowed_tools: string[];
            /** Memory Namespace */
            memory_namespace: string;
            /**
             * Triggers
             * @default []
             */
            triggers: {
                [key: string]: unknown;
            }[];
            /**
             * Schedules
             * @default []
             */
            schedules: {
                [key: string]: unknown;
            }[];
            /**
             * Permissions
             * @default {}
             */
            permissions: {
                [key: string]: unknown;
            };
            /**
             * Ui Metadata
             * @default {}
             */
            ui_metadata: {
                [key: string]: unknown;
            };
            /**
             * State Schema
             * @default {}
             */
            state_schema: {
                [key: string]: unknown;
            };
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Last Activity At */
            last_activity_at?: string | null;
        } & {
            [key: string]: unknown;
        };
        /** AgentCard */
        AgentCard: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Icon */
            icon: string;
            /** Short Purpose */
            short_purpose: string;
            /** Category */
            category: string;
            /** Enabled */
            enabled: boolean;
            status: components["schemas"]["AgentStatus"];
            privacy_class: components["schemas"]["PrivacyClass"];
            model_policy: components["schemas"]["ModelPolicy"];
            /** Last Activity At */
            last_activity_at?: string | null;
            /**
             * Current Focus
             * @default
             */
            current_focus: string;
            /** Outstanding Tasks */
            outstanding_tasks: number;
            /** Warning */
            warning?: string | null;
            /**
             * Metrics
             * @default {}
             */
            metrics: {
                [key: string]: unknown;
            };
            /**
             * Ui Metadata
             * @default {}
             */
            ui_metadata: {
                [key: string]: unknown;
            };
        };
        /** AgentCreate */
        AgentCreate: {
            /** Id */
            id?: string | null;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Icon
             * @default ◌
             */
            icon: string;
            /**
             * Category
             * @default general
             */
            category: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * System Instructions
             * @default
             */
            system_instructions: string;
            /** @default PERSONAL */
            privacy_class: components["schemas"]["PrivacyClass"];
            /** @default BALANCED */
            model_policy: components["schemas"]["ModelPolicy"];
            /** Allowed Tools */
            allowed_tools?: string[];
            /** Memory Namespace */
            memory_namespace?: string | null;
            /** Triggers */
            triggers?: {
                [key: string]: unknown;
            }[];
            /** Schedules */
            schedules?: {
                [key: string]: unknown;
            }[];
            /** Permissions */
            permissions?: {
                [key: string]: unknown;
            };
            /** Ui Metadata */
            ui_metadata?: {
                [key: string]: unknown;
            };
            /** State Schema */
            state_schema?: {
                [key: string]: unknown;
            };
        };
        /** AgentExecutionResponse */
        AgentExecutionResponse: {
            /**
             * Intent
             * @constant
             */
            intent: "agent_execution";
            /** Task Id */
            task_id: string;
            status: components["schemas"]["TaskStatus"];
            /** Reply */
            reply: string;
            structured_result: components["schemas"]["StructuredResult"];
            model_selected?: components["schemas"]["ModelInfo"] | null;
            policy: components["schemas"]["ModelPolicy"];
            /** Routing Reason */
            routing_reason: string;
            /** Duration Ms */
            duration_ms: number;
            /** Success */
            success: boolean;
            /** Error */
            error?: string | null;
        };
        /** AgentPatch */
        AgentPatch: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Icon */
            icon?: string | null;
            /** Category */
            category?: string | null;
            /** Enabled */
            enabled?: boolean | null;
            status?: components["schemas"]["AgentStatus"] | null;
            /** System Instructions */
            system_instructions?: string | null;
            privacy_class?: components["schemas"]["PrivacyClass"] | null;
            model_policy?: components["schemas"]["ModelPolicy"] | null;
            /** Allowed Tools */
            allowed_tools?: string[] | null;
            /** Triggers */
            triggers?: {
                [key: string]: unknown;
            }[] | null;
            /** Schedules */
            schedules?: {
                [key: string]: unknown;
            }[] | null;
            /** Permissions */
            permissions?: {
                [key: string]: unknown;
            } | null;
            /** Ui Metadata */
            ui_metadata?: {
                [key: string]: unknown;
            } | null;
            /** State Schema */
            state_schema?: {
                [key: string]: unknown;
            } | null;
        };
        /** AgentState */
        AgentState: {
            /** Agent Id */
            agent_id: string;
            /** Stable Facts */
            stable_facts: {
                [key: string]: unknown;
            };
            /** Current State */
            current_state: {
                [key: string]: unknown;
            };
            /** Structured Data */
            structured_data: {
                [key: string]: unknown;
            };
            /** Updated At */
            updated_at: string;
        };
        /**
         * AgentStatus
         * @enum {string}
         */
        AgentStatus: "IDLE" | "WORKING" | "WAITING" | "BLOCKED" | "ERROR" | "DISABLED";
        /** ArchiveResponse */
        ArchiveResponse: {
            /** Ok */
            ok: boolean;
            /** Archived */
            archived: boolean;
        };
        /** CreateAgentMessageResponse */
        CreateAgentMessageResponse: {
            /**
             * Intent
             * @constant
             */
            intent: "create_agent";
            agent?: components["schemas"]["Agent"] | null;
            proposed_agent?: components["schemas"]["DerivedAgentManifest"] | null;
            /** Response */
            response?: string | null;
        };
        /** DashboardOverview */
        DashboardOverview: {
            /** System */
            system: {
                [key: string]: unknown;
            };
            /** Agents */
            agents: components["schemas"]["AgentCard"][];
            /** Running Tasks */
            running_tasks: components["schemas"]["Task"][];
            /** Queued Tasks */
            queued_tasks: components["schemas"]["Task"][];
            /** Warnings */
            warnings: ({
                [key: string]: unknown;
            } | string)[];
            /** Projects Needing Attention */
            projects_needing_attention: components["schemas"]["ProjectSummary"][];
            /** Recent Activity */
            recent_activity: components["schemas"]["Activity"][];
            /** Models */
            models: components["schemas"]["ModelInfo"][];
        };
        /** DerivedAgentManifest */
        DerivedAgentManifest: {
            /** Id */
            id?: string | null;
            /** Name */
            name: string;
            /**
             * Description
             * @default
             */
            description: string;
            /**
             * Icon
             * @default ◌
             */
            icon: string;
            /**
             * Category
             * @default general
             */
            category: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * System Instructions
             * @default
             */
            system_instructions: string;
            /** @default PERSONAL */
            privacy_class: components["schemas"]["PrivacyClass"];
            /** @default BALANCED */
            model_policy: components["schemas"]["ModelPolicy"];
            /** Allowed Tools */
            allowed_tools?: string[];
            /** Memory Namespace */
            memory_namespace?: string | null;
            /** Triggers */
            triggers?: {
                [key: string]: unknown;
            }[];
            /** Schedules */
            schedules?: {
                [key: string]: unknown;
            }[];
            /** Permissions */
            permissions?: {
                [key: string]: unknown;
            };
            /** Ui Metadata */
            ui_metadata?: {
                [key: string]: unknown;
            };
            /** State Schema */
            state_schema?: {
                [key: string]: unknown;
            };
        };
        /** DryRunExecutionResponse */
        DryRunExecutionResponse: {
            /**
             * Intent
             * @constant
             */
            intent: "agent_execution";
            /** Would Execute Model */
            would_execute_model: boolean;
        };
        /** Event */
        Event: {
            /** Id */
            id: number;
            /** Agent Id */
            agent_id?: string | null;
            /** Type */
            type: string;
            /** Summary */
            summary: string;
            /**
             * Payload
             * @default {}
             */
            payload: {
                [key: string]: unknown;
            };
            privacy_class: components["schemas"]["PrivacyClass"];
            /** Created At */
            created_at: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthUpdateResponse */
        HealthUpdateResponse: {
            /**
             * Intent
             * @constant
             */
            intent: "health_update";
            /** Execution */
            execution?: "deterministic_fast_path" | null;
            /** Response */
            response?: string | null;
            /** Update */
            update?: {
                [key: string]: unknown;
            } | null;
        };
        /** ListAgentsMessageResponse */
        ListAgentsMessageResponse: {
            /**
             * Intent
             * @constant
             */
            intent: "list_agents";
            /** Agents */
            agents: components["schemas"]["AgentCard"][];
        };
        /** MediaUpdateResponse */
        MediaUpdateResponse: {
            /**
             * Intent
             * @constant
             */
            intent: "media_update";
            /** Execution */
            execution?: "deterministic_fast_path" | null;
            /** Response */
            response?: string | null;
            /** Update */
            update?: {
                [key: string]: unknown;
            } | null;
        };
        /** MessageIn */
        MessageIn: {
            /** Message */
            message: string;
            /**
             * Dry Run
             * @default false
             */
            dry_run: boolean;
            /**
             * Require Model
             * @default false
             */
            require_model: boolean;
        };
        /** ModelInfo */
        ModelInfo: {
            /** Id */
            id: string;
            /** Provider */
            provider: string;
            /** Model */
            model: string;
            /** Base Url */
            base_url?: string | null;
            /**
             * Capabilities
             * @default []
             */
            capabilities: string[];
            /**
             * Privacy Allowed
             * @default []
             */
            privacy_allowed: components["schemas"]["PrivacyClass"][];
            /**
             * Cost Class
             * @default unknown
             */
            cost_class: string;
            /**
             * Latency Class
             * @default unknown
             */
            latency_class: string;
            /**
             * Enabled
             * @default true
             */
            enabled: boolean;
            /**
             * Priority
             * @default 100
             */
            priority: number;
            /**
             * Metadata
             * @default {}
             */
            metadata: {
                [key: string]: unknown;
            };
        };
        /**
         * ModelPolicy
         * @enum {string}
         */
        ModelPolicy: "LOCAL_ONLY" | "CHEAP_FAST" | "BALANCED" | "DEEP_REASONING" | "CODING" | "CUSTOM";
        /**
         * PrivacyClass
         * @enum {string}
         */
        PrivacyClass: "PUBLIC_OR_GENERAL" | "PERSONAL" | "PRIVATE" | "WORK_RESTRICTED";
        /** ProjectSummary */
        ProjectSummary: {
            /** Id */
            id?: number | null;
            /** Project Alias */
            project_alias: string;
            /** Generated At */
            generated_at: string;
            /**
             * Project Type
             * @enum {string}
             */
            project_type: "work" | "personal";
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "blocked" | "paused" | "completed";
            /**
             * Progress Signal
             * @enum {string}
             */
            progress_signal: "moved_forward" | "neutral" | "blocked";
            /**
             * Session Summary
             * @default
             */
            session_summary: string;
            /**
             * Accomplishments
             * @default []
             */
            accomplishments: string[];
            /**
             * Blockers
             * @default []
             */
            blockers: string[];
            /**
             * Next Actions
             * @default []
             */
            next_actions: string[];
            /**
             * Decisions
             * @default []
             */
            decisions: string[];
            /**
             * Attention Next Session
             * @default
             */
            attention_next_session: string;
            /**
             * Needs Followup
             * @default false
             */
            needs_followup: boolean;
            /**
             * Tags
             * @default []
             */
            tags: string[];
            /** @default WORK_RESTRICTED */
            privacy_class: components["schemas"]["PrivacyClass"];
            /** Raw */
            raw?: {
                [key: string]: unknown;
            } | null;
            /** Created At */
            created_at?: string | null;
        };
        /** ProjectSummaryIn */
        ProjectSummaryIn: {
            /** Project Alias */
            project_alias: string;
            /** Generated At */
            generated_at: string;
            /**
             * Project Type
             * @enum {string}
             */
            project_type: "work" | "personal";
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "blocked" | "paused" | "completed";
            /**
             * Progress Signal
             * @default neutral
             * @enum {string}
             */
            progress_signal: "moved_forward" | "neutral" | "blocked";
            /**
             * Session Summary
             * @default
             */
            session_summary: string;
            /** Accomplishments */
            accomplishments?: string[];
            /** Blockers */
            blockers?: string[];
            /** Next Actions */
            next_actions?: string[];
            /** Decisions */
            decisions?: string[];
            /**
             * Attention Next Session
             * @default
             */
            attention_next_session: string;
            /**
             * Needs Followup
             * @default false
             */
            needs_followup: boolean;
            /** Tags */
            tags?: string[];
            /** @default WORK_RESTRICTED */
            privacy_class: components["schemas"]["PrivacyClass"];
        };
        /** ProjectSummaryIngestResponse */
        ProjectSummaryIngestResponse: {
            /** Ok */
            ok: boolean;
            /** Project Alias */
            project_alias: string;
        };
        /** RunIn */
        RunIn: {
            /** Task */
            task: string;
            /**
             * Task Category
             * @default general
             */
            task_category: string;
            /**
             * Require Model
             * @default true
             */
            require_model: boolean;
            /**
             * Async Run
             * @default false
             */
            async_run: boolean;
        };
        /** StructuredResult */
        StructuredResult: {
            /** Reply */
            reply: string;
            /**
             * State Updates
             * @default []
             */
            state_updates: {
                [key: string]: unknown;
            }[];
            /**
             * Facts To Add
             * @default []
             */
            facts_to_add: {
                [key: string]: unknown;
            }[];
            /**
             * Facts To Remove
             * @default []
             */
            facts_to_remove: {
                [key: string]: unknown;
            }[];
            /**
             * Tasks To Create
             * @default []
             */
            tasks_to_create: {
                [key: string]: unknown;
            }[];
            /**
             * Tasks To Update
             * @default []
             */
            tasks_to_update: {
                [key: string]: unknown;
            }[];
            /**
             * Events
             * @default []
             */
            events: {
                [key: string]: unknown;
            }[];
            /**
             * Requires Confirmation
             * @default false
             */
            requires_confirmation: boolean;
        };
        /** SystemStatus */
        SystemStatus: {
            /** Status */
            status: string;
            /** Service */
            service: string;
            /** Db */
            db: string;
            /** Agents By Status */
            agents_by_status: {
                [key: string]: number;
            };
            /** Time */
            time: string;
        };
        /** Task */
        Task: {
            /** Id */
            id: string;
            /** Agent Id */
            agent_id: string;
            /** Title */
            title: string;
            /**
             * Description
             * @default
             */
            description: string;
            status: components["schemas"]["TaskStatus"];
            /**
             * Priority
             * @default 3
             */
            priority: number;
            /** Due At */
            due_at?: string | null;
            /** Created At */
            created_at: string;
            /** Updated At */
            updated_at: string;
            /** Completed At */
            completed_at?: string | null;
        };
        /**
         * TaskStatus
         * @enum {string}
         */
        TaskStatus: "QUEUED" | "RUNNING" | "WAITING_FOR_USER" | "SUCCEEDED" | "FAILED" | "CANCELLED" | "OPEN" | "COMPLETED";
        /** UnroutedMessageResponse */
        UnroutedMessageResponse: {
            /**
             * Intent
             * @constant
             */
            intent: "unrouted";
            /** Response */
            response: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    system_status_api_v1_system_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SystemStatus"];
                };
            };
        };
    };
    list_agents_api_v1_agents_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentCard"][];
                };
            };
        };
    };
    create_agent_api_v1_agents_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    derive_agent_api_v1_agents_derive_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DerivedAgentManifest"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    read_agent_api_v1_agents__agent_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    archive_agent_api_v1_agents__agent_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ArchiveResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_agent_api_v1_agents__agent_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentPatch"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Agent"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_state_api_v1_agents__agent_id__state_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentState"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_tasks_api_v1_agents__agent_id__tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_activity_api_v1_agents__agent_id__activity_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    agent_message_api_v1_agents__agent_id__message_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAgentsMessageResponse"] | components["schemas"]["CreateAgentMessageResponse"] | components["schemas"]["UnroutedMessageResponse"] | components["schemas"]["MediaUpdateResponse"] | components["schemas"]["HealthUpdateResponse"] | components["schemas"]["AgentExecutionResponse"] | components["schemas"]["DryRunExecutionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    route_message_api_v1_message_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MessageIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListAgentsMessageResponse"] | components["schemas"]["CreateAgentMessageResponse"] | components["schemas"]["UnroutedMessageResponse"] | components["schemas"]["MediaUpdateResponse"] | components["schemas"]["HealthUpdateResponse"] | components["schemas"]["AgentExecutionResponse"] | components["schemas"]["DryRunExecutionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_agent_api_v1_agents__agent_id__run_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                agent_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentExecutionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    tasks_api_v1_tasks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Task"][];
                };
            };
        };
    };
    activity_api_v1_activity_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Activity"][];
                };
            };
        };
    };
    events_api_v1_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
        };
    };
    models_api_v1_models_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ModelInfo"][];
                };
            };
        };
    };
    dashboard_overview_api_v1_dashboard_overview_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DashboardOverview"];
                };
            };
        };
    };
    project_summaries_api_v1_project_summaries_get: {
        parameters: {
            query?: {
                project_alias?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_project_summary_api_v1_project_summaries_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectSummaryIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummaryIngestResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    stream_api_v1_stream_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server-Sent Events stream */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": string;
                };
            };
        };
    };
}
